### ISSUE TITLE
`prisma.use` is deprecated

### ISSUE THREAD

**Issue by sorenhansendk** [tubbo/prisma-slug#3]
Hi @tubbo, thank you for a very cool Prisma extension! It works pretty well.

I have tried to implement `prisma-slug` in with v5 of Prisma, but it warns against the `.use` method.

It looks like the Prisma-team has deprecated it. Can you please provide `prisma-slug` as an extension?

<pre>
@deprecated — since 4.16.0. For new code, prefer client extensions instead.
</pre>

**Comment by tubbo** [comment]
Hey @sorenhansendk, to be honest I don't really use Prisma anymore, so haven't kept up to date on the API changes. I don't have much time for updating this repo anymore as I'm not even a developer by trade these days. If you'd like to contribute something to pass those deprecation warnings, I'd be happy to merge/release it and possibly even transfer ownership of the project to you (as long as you'd be cool with maintaining it) as I'm likely not the best steward for this project anymore.

**Comment by sorenhansendk** [comment]
@tubbo Thank for the reply. I'm sorry to hear that, but I'm also unable to continue maintaining it.
